import { IconCurrencySolana } from "@tabler/icons-react";
import { EditorDocument } from "@tutorialkit/components-react/core";
import { stripIndent } from "./utils/stripIndent";

export interface Course {
  slug: string;
  title: string;
  description: string;
  icon: JSX.Element;
  tooltip: string;
  installOnStartup: boolean;
  maxSteps: number;
  steps: Array<{
    path: string;
  }>;
  initialCode: Record<string, EditorDocument>;
}

export const courses = [
  {
    slug: "intro-to-solana",
    title: "Intro to Solana",
    description:
      "Learn how to interact with widely used SDKs and development tools through guided courses.",
    icon: <IconCurrencySolana className="h-7 w-7" />,
    tooltip: "",
    installOnStartup: true,
    maxSteps: 4,
    steps: [
      {
        path: "/sample-course/intro-1.md",
      },
      {
        path: "/sample-course/intro-2.md",
      },
      {
        path: "/sample-course/intro-3.md",
      },
      {
        path: "/sample-course/intro-4.md",
      },
    ],
    initialCode: {
      "/src/index.ts": {
        filePath: "/src/index.ts",
        loading: false,
        value: stripIndent(`
                  import { Connection } from "@solana/web3.js";
                  
                  async function main() {
                    const connection = new Connection("https://api.devnet.solana.com");
                    const version = await connection.getVersion();
                    console.log("Solana version: ", version);
                  }
                  main();
                `),
      },
      "/package.json": {
        filePath: "/package.json",
        loading: false,
        value: stripIndent(`
        {
            "name": "intro-to-solana",
            "version": "1.0.0",
            "description": "Generated by Zircon!",
            "main": "src/index.ts",
            "scripts": {
              "start": "ts-node src/index.ts"
            },
            "dependencies": {
              "servor": "4.0.2",
              "typescript": "^5.2.2",
              "@sqds/multisig": "^2.1.2",
              "@solana/web3.js": "^1.87.6"
            },
            "devDependencies": {
                "ts-node": "^10.9.1"
            }
          }
                `),
      },
    },
  },
];
